try {
  const things = ["car", "shoe", "computer"];
  console.log(things[4].length);
} catch (error) {
  console.log("something went wrong");
}
